#!/bin/bash

while read -r file; do
  case "$1" in
    w) set-wallpaper "${file}" ;;
    d) mv "${file}" "$HOME/.local/share/Trash/files/" ;;
    r) convert -rotate 90 "${file}" "${file}" ;;
    R) convert -rotate -90 "${file}" "${file}" ;;
    c) cat "${file}" | xclip -sel clip -t image/png ;;
  esac
done
