#!/bin/bash

while read file
do
	case "$1" in
		w) setbg "${file}" ;;
		d) mv "${file}" ~/.local/share/Trash/files/ ;;
		r) convert -rotate 90 "${file}" "${file}" ;;
		R) convert -rotate -90 "${file}" "${file}" ;;
		c) cat "${file}" | xclip -sel clip -t image/png ;;
	esac
done
