#!/usr/bin/bash
#
# ~/.xinitrc
# Executed by startx (run your window manager from here)

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

fallback_session=dwm
session=$1
[[ -z "$session" ]] && session=$fallback_session

if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
  . "$HOME/.xprofile"
fi

# Start Window Manager here
case ${session} in
  i3|i3wm) exec i3 ;;
  mate) exec mate-session ;;
  kde) exec startplasma-x11 ;;
  xfce|xfce4) exec startxfce4 ;;
  dwm)
    # Remember that lines following a command using exec would be ignored.
    # For example, to start xscreensaver in the background and then start openbox, use the following:
    # xscreensaver &
    # exec openbox-session
    ${STATUSBAR} &
    exec dwm ;;
  # No known session, try to run it as command
  *) exec "$session" ;;
esac
