#!/bin/bash
#
# Take a webcam shot when someone login

PIXPATH=${HOME}/vault/pix/screenshots/private/login-shot
pic_name=$(date +"%Y.%m.%d %I:%M:%S %p %A")

fswebcam -q --no-banner -r 1366x768 ${PIXPATH}/"${pic_name}.png"

# copy it to the clipboard
cat ${PIXPATH}/${pic_name}.png | xclip -sel clipboard -t image/png
