#!/bin/bash

update_sb="pkill -RTMIN+5 dwmblocks"

value="$2"
[[ -z "${value}" ]] && value=1

case "$1" in
  up) xbacklight -time 0 -inc 3; ${update_sb} ;;
  down) xbacklight -time 0 -dec 3; ${update_sb} ;;
  set) xbacklight -time 0 -set ${value}; ${update_sb} ;;
esac
